package PrismLayerTool;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */


import java.text.NumberFormat;
import star.common.Simulation;

/**
 *
 * @author peterb
 */
public class PrismLayerCalcFrame extends javax.swing.JFrame {

    Simulation _sim;
    /**
     * Creates new form PrismLayerCalcFrame
     */
    public PrismLayerCalcFrame(Simulation sim) {
        _sim = sim;
        initComponents();
    }
    public PrismLayerCalcFrame() {
        initComponents();
    }
    
    private void log( String msg ) {
        _sim.println("[PrismLayerCalc]: " + msg);
    }

    private int getStretchingFunc() {
        return stretchFuncCombo.getSelectedIndex();
    }
    
    private int getDistributionMode() {
        return distModeCombo.getSelectedIndex();
    }
    
    private int getNumLayers() {
        return Integer.parseInt(numLayersBox.getText());
    }
    
    private double getTotalThickness() {
        return Double.parseDouble(totalThicknessBox.getText());
    }
    
    private double getNearWallThickness() {
        return Double.parseDouble(stretchParameterBox.getText());
    }
    
    private double getStretchingValue() {
        return Double.parseDouble(nearWallBox.getText());
    }
    
    private void updateTextValues(int Layers, double[] other) {
        numLayersBox.setText(Integer.toString(Layers));
        totalThicknessBox.setText(Double.toString(other[0]));
        stretchParameterBox.setText(Double.toString(other[1]));
        nearWallBox.setText(Double.toString(other[2]));
    }
    
    private double calcNearWallThickness(int N, double totalThick, double stretch, int mode) {
        double val = 0.0;
        switch (mode) {
            case 0: // GP
                val = calcNearWallThicknessGP( N, totalThick, stretch);
                break;
            case 1: //HT
                val = calcNearWallThicknessHT( N, totalThick, stretch);
                break;
        }
        return val;
    }
    
    private double calcStretchingRatio( int N, double totalThick, double nearWall, int mode) {
        double val = 0.0;
        switch (mode) {
            case 0: // GP
                val = calcStretchingRatioGP( N, totalThick, nearWall);
                break;
            case 1: //HT
                val = calcStretchingRatioHT( N, totalThick, nearWall);
                break;
        }
        return val;
        
    }
    private double calcNearWallThicknessGP(int N, double totalThick, double stretch) {
        return totalThick*(1.0 + Math.tanh(-stretch*(1.0 - 1.0/( (double) N )))/Math.tanh(stretch) );   
    }
    
    private double calcNearWallThicknessHT(int N, double totalThick, double stretch) {
        return totalThick*(Math.pow(stretch, (double) N)-1.0)/(stretch-1.0);   
    }
    
    private double calcStretchingRatioGP( int N, double totalThick, double nearWall) {
        double stretch = 1.5;
        for (int i=0; i<20; i++) {
            stretch = Math.pow( (totalThick/nearWall)*(stretch-1.0) + 1.0 , 1.0/( (double) N) );
        }
        return stretch;
    }
    
    private double calcStretchingRatioHT( int N, double totalThick, double nearWall) {
        double Fs = 1.0;
        double s1 = nearWall/totalThick;
        for (int i=0; i<50; i++) {
            Fs = -1.0*atanh( (s1-1.0)*Math.tanh(Fs) )/(1.0 - 1.0/( (double) N ));
        }
        return Fs;
    }
    
    private double atanh( double x ) {
        return 0.5*Math.log( (x+1.0)/(x-1.0) );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prismLayerToolTitle = new javax.swing.JLabel();
        stretchFuncLabel = new javax.swing.JLabel();
        distModeLabel = new javax.swing.JLabel();
        numLayersLabel = new javax.swing.JLabel();
        totalThicknessLabel = new javax.swing.JLabel();
        stretchParameterLabel = new javax.swing.JLabel();
        nearWallLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        stretchFuncCombo = new javax.swing.JComboBox();
        distModeCombo = new javax.swing.JComboBox();
        numLayersBox = new javax.swing.JFormattedTextField(NumberFormat.getIntegerInstance());
        totalThicknessBox = new javax.swing.JFormattedTextField(NumberFormat.getNumberInstance());
        stretchParameterBox = new javax.swing.JFormattedTextField(NumberFormat.getNumberInstance());
        nearWallBox = new javax.swing.JFormattedTextField(NumberFormat.getNumberInstance());
        closeButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        thicknessRatioLabel = new javax.swing.JLabel();
        thicknessRatioBox = new javax.swing.JFormattedTextField(NumberFormat.getNumberInstance());
        meshOpLabel = new javax.swing.JLabel();
        meshOpCombo = new javax.swing.JComboBox();
        calcButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(445, 350));

        prismLayerToolTitle.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(prismLayerToolTitle, org.openide.util.NbBundle.getMessage(PrismLayerCalcFrame.class, "PrismLayerCalcFrame.prismLayerToolTitle.text")); // NOI18N

        stretchFuncLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(stretchFuncLabel, org.openide.util.NbBundle.getMessage(PrismLayerCalcFrame.class, "PrismLayerCalcFrame.stretchFuncLabel.text")); // NOI18N

        distModeLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(distModeLabel, org.openide.util.NbBundle.getMessage(PrismLayerCalcFrame.class, "PrismLayerCalcFrame.distModeLabel.text")); // NOI18N

        numLayersLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(numLayersLabel, org.openide.util.NbBundle.getMessage(PrismLayerCalcFrame.class, "PrismLayerCalcFrame.numLayersLabel.text")); // NOI18N

        totalThicknessLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(totalThicknessLabel, org.openide.util.NbBundle.getMessage(PrismLayerCalcFrame.class, "PrismLayerCalcFrame.totalThicknessLabel.text")); // NOI18N

        stretchParameterLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(stretchParameterLabel, org.openide.util.NbBundle.getMessage(PrismLayerCalcFrame.class, "PrismLayerCalcFrame.stretchParameterLabel.text")); // NOI18N

        nearWallLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(nearWallLabel, org.openide.util.NbBundle.getMessage(PrismLayerCalcFrame.class, "PrismLayerCalcFrame.nearWallLabel.text")); // NOI18N

        stretchFuncCombo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        stretchFuncCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Geometric Progression", "Hyperbolic Tangent" }));
        stretchFuncCombo.setSelectedIndex(0);

        distModeCombo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        distModeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Stretch Factor", "Wall Thickness", "Thickness Ratio" }));
        distModeCombo.setSelectedIndex(0);
        distModeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                distModeComboActionPerformed(evt);
            }
        });

        numLayersBox.setText(org.openide.util.NbBundle.getMessage(PrismLayerCalcFrame.class, "PrismLayerCalcFrame.numLayersBox.text")); // NOI18N
        numLayersBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        numLayersBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numLayersBoxActionPerformed(evt);
            }
        });

        totalThicknessBox.setText(org.openide.util.NbBundle.getMessage(PrismLayerCalcFrame.class, "PrismLayerCalcFrame.totalThicknessBox.text")); // NOI18N
        totalThicknessBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        stretchParameterBox.setText(org.openide.util.NbBundle.getMessage(PrismLayerCalcFrame.class, "PrismLayerCalcFrame.stretchParameterBox.text")); // NOI18N
        stretchParameterBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        stretchParameterBox.setEditable(true);

        nearWallBox.setText(org.openide.util.NbBundle.getMessage(PrismLayerCalcFrame.class, "PrismLayerCalcFrame.nearWallBox.text")); // NOI18N
        nearWallBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        nearWallBox.setEditable (false);

        closeButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(closeButton, org.openide.util.NbBundle.getMessage(PrismLayerCalcFrame.class, "PrismLayerCalcFrame.closeButton.text")); // NOI18N
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        updateButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(updateButton, org.openide.util.NbBundle.getMessage(PrismLayerCalcFrame.class, "PrismLayerCalcFrame.updateButton.text")); // NOI18N
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        thicknessRatioLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(thicknessRatioLabel, org.openide.util.NbBundle.getMessage(PrismLayerCalcFrame.class, "PrismLayerCalcFrame.thicknessRatioLabel.text")); // NOI18N

        thicknessRatioBox.setText(org.openide.util.NbBundle.getMessage(PrismLayerCalcFrame.class, "PrismLayerCalcFrame.thicknessRatioBox.text")); // NOI18N
        thicknessRatioBox.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        thicknessRatioBox.setEditable (false);

        meshOpLabel.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(meshOpLabel, org.openide.util.NbBundle.getMessage(PrismLayerCalcFrame.class, "PrismLayerCalcFrame.meshOpLabel.text")); // NOI18N

        meshOpCombo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        meshOpCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mesh Operation" }));

        calcButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(calcButton, org.openide.util.NbBundle.getMessage(PrismLayerCalcFrame.class, "PrismLayerCalcFrame.calcButton.text")); // NOI18N
        calcButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalThicknessLabel)
                            .addComponent(stretchFuncLabel)
                            .addComponent(distModeLabel)
                            .addComponent(numLayersLabel)
                            .addComponent(stretchParameterLabel)
                            .addComponent(nearWallLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(stretchFuncCombo, 0, 200, Short.MAX_VALUE)
                            .addComponent(distModeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numLayersBox)
                            .addComponent(totalThicknessBox)
                            .addComponent(stretchParameterBox)
                            .addComponent(nearWallBox)))
                    .addComponent(jSeparator3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(thicknessRatioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(thicknessRatioBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(calcButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(prismLayerToolTitle)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(meshOpLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(meshOpCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prismLayerToolTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(stretchFuncLabel)
                    .addComponent(stretchFuncCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(distModeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(distModeCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numLayersLabel)
                    .addComponent(numLayersBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalThicknessBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalThicknessLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stretchParameterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stretchParameterLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(nearWallBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nearWallLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thicknessRatioLabel)
                    .addComponent(thicknessRatioBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(meshOpLabel)
                    .addComponent(meshOpCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(updateButton)
                    .addComponent(calcButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numLayersBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numLayersBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numLayersBoxActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        int distMode = distModeCombo.getSelectedIndex();
        int stretchFun = stretchFuncCombo.getSelectedIndex();
        
        int N = getNumLayers();
        double[] vals = {1.0, 1.0, 1.0};
        vals[0] = getTotalThickness();
        vals[1] = getNearWallThickness();
        vals[2] = getStretchingValue();
        
        switch (distMode) {
            case 0: // Stretch Factor
                vals[1] = calcNearWallThickness( N, vals[0], vals[2], stretchFun );
                break;
            case 1: // Near Wall Thickness
                vals[2] = calcStretchingRatio( N, vals[0], vals[1], stretchFun );
                break;
        }
        updateTextValues(N, vals);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void distModeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_distModeComboActionPerformed
        // TODO add your handling code here:
        int distMode = distModeCombo.getSelectedIndex();
        switch (distMode) {
            case 0:
                stretchParameterBox.setEditable(true);
                nearWallBox.setEditable(false);
                thicknessRatioBox.setEditable(false);
                break;
            case 1:
                stretchParameterBox.setEditable(false);
                nearWallBox.setEditable(true);
                thicknessRatioBox.setEditable(false);
                break;
            case 2:
                stretchParameterBox.setEditable(false);
                nearWallBox.setEditable(false);
                thicknessRatioBox.setEditable(true);
                break;
        }
    }//GEN-LAST:event_distModeComboActionPerformed

    private void calcButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calcButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrismLayerCalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrismLayerCalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrismLayerCalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrismLayerCalcFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrismLayerCalcFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JComboBox distModeCombo;
    private javax.swing.JLabel distModeLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JComboBox meshOpCombo;
    private javax.swing.JLabel meshOpLabel;
    private javax.swing.JFormattedTextField nearWallBox;
    private javax.swing.JLabel nearWallLabel;
    private javax.swing.JFormattedTextField numLayersBox;
    private javax.swing.JLabel numLayersLabel;
    private javax.swing.JLabel prismLayerToolTitle;
    private javax.swing.JComboBox stretchFuncCombo;
    private javax.swing.JLabel stretchFuncLabel;
    private javax.swing.JFormattedTextField stretchParameterBox;
    private javax.swing.JLabel stretchParameterLabel;
    private javax.swing.JFormattedTextField thicknessRatioBox;
    private javax.swing.JLabel thicknessRatioLabel;
    private javax.swing.JFormattedTextField totalThicknessBox;
    private javax.swing.JLabel totalThicknessLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
